name: Wakatime Stats

on:
  schedule:
    - cron: '00 12 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update coding stats in repo
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_TIMEZONE: "True"
          SHOW_COMMIT: "True"
          SHIW_LANGUAGE: "True"
          SHOW_EDITORS: "True"
          SHOW_OS: "True"
          SYMBOL_VERSION: "2"
