name: Wakatime Stats

on:
  schedule:
    - cron: '00 12 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update coding stats in repo
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_TIMEZONE: "True"
          SHOW_LANGUAGE: "True"
          SHOW_EDITORS: "True"
          SHOW_OS: "True"
          SYMBOL_VERSION: "2"
          SHOW_LANGUAGE_PER_REPO: "False"
          SHOW_PROJECTS: "False"
          SHOW_LINES_OF_CODE: "False"
          SHOW_LOC_CHART: "False"
          SHOW_PROFILE_VIEWS: "False"
          SHOW_TOTAL_CODE_TIME: "False"
          SHOW_SHORT_INFO: "False"
          SHOW_COMMIT: "False"
          SHOW_DAYS_OF_WEEK: "False"
          SHOW_UPDATED_DATE: "False"
